Update patch set 9
Patch Set 9: Verified-1

(1 comment)

opendaylight-user@root>feature:install odl-transportpce
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=odl-transportpce; type=karaf.feature; version="[0.5.0.SNAPSHOT,0.5.0.SNAPSHOT]"; filter:="(&(osgi.identity=odl-transportpce)(type=karaf.feature)(version>=0.5.0.SNAPSHOT)(version<=0.5.0.SNAPSHOT))" [caused by: Unable to resolve odl-transportpce/0.5.0.SNAPSHOT: missing requirement [odl-transportpce/0.5.0.SNAPSHOT] osgi.identity; osgi.identity=org.opendaylight.transportpce.servicehandler; type=osgi.bundle; version="[0.5.0.SNAPSHOT,0.5.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.opendaylight.transportpce.servicehandler/0.5.0.SNAPSHOT: missing requirement [org.opendaylight.transportpce.servicehandler/0.5.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opendaylight.transportpce.renderer)(version>=0.5.0)(!(version>=1.0.0)))" [caused by: Unable to resolve org.opendaylight.transportpce.renderer/0.5.0.SNAPSHOT: missing requirement [org.opendaylight.transportpce.renderer/0.5.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.renderer.rev171017.service.implementation.request.input)"]]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:378)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:332)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve odl-transportpce/0.5.0.SNAPSHOT: missing requirement [odl-transportpce/0.5.0.SNAPSHOT] osgi.identity; osgi.identity=org.opendaylight.transportpce.servicehandler; type=osgi.bundle; version="[0.5.0.SNAPSHOT,0.5.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.opendaylight.transportpce.servicehandler/0.5.0.SNAPSHOT: missing requirement [org.opendaylight.transportpce.servicehandler/0.5.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opendaylight.transportpce.renderer)(version>=0.5.0)(!(version>=1.0.0)))" [caused by: Unable to resolve org.opendaylight.transportpce.renderer/0.5.0.SNAPSHOT: missing requirement [org.opendaylight.transportpce.renderer/0.5.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.renderer.rev171017.service.implementation.request.input)"]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.opendaylight.transportpce.servicehandler/0.5.0.SNAPSHOT: missing requirement [org.opendaylight.transportpce.servicehandler/0.5.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opendaylight.transportpce.renderer)(version>=0.5.0)(!(version>=1.0.0)))" [caused by: Unable to resolve org.opendaylight.transportpce.renderer/0.5.0.SNAPSHOT: missing requirement [org.opendaylight.transportpce.renderer/0.5.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.renderer.rev171017.service.implementation.request.input)"]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 13 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.opendaylight.transportpce.renderer/0.5.0.SNAPSHOT: missing requirement [org.opendaylight.transportpce.renderer/0.5.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.renderer.rev171017.service.implementation.request.input)"
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 14 more
Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=odl-transportpce; type=karaf.feature; version="[0.5.0.SNAPSHOT,0.5.0.SNAPSHOT]"; filter:="(&(osgi.identity=odl-transportpce)(type=karaf.feature)(version>=0.5.0.SNAPSHOT)(version<=0.5.0.SNAPSHOT))" [caused by: Unable to resolve odl-transportpce/0.5.0.SNAPSHOT: missing requirement [odl-transportpce/0.5.0.SNAPSHOT] osgi.identity; osgi.identity=org.opendaylight.transportpce.servicehandler; type=osgi.bundle; version="[0.5.0.SNAPSHOT,0.5.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.opendaylight.transportpce.servicehandler/0.5.0.SNAPSHOT: missing requirement [org.opendaylight.transportpce.servicehandler/0.5.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.opendaylight.transportpce.renderer)(version>=0.5.0)(!(version>=1.0.0)))" [caused by: Unable to resolve org.opendaylight.transportpce.renderer/0.5.0.SNAPSHOT: missing requirement [org.opendaylight.transportpce.renderer/0.5.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.renderer.rev171017.service.implementation.request.input)"]]]

Patch-set: 9
Label: Verified=-1