Update patch set 2
Patch Set 2:

something is broken with netconf
org.apache.felix.resolver.reason.ReasonException: Unable to resolve
root: missing requirement [root] osgi.identity; osgi.identity=f10e4260-a93a-4d78-beb5-cb17edbd7ce5;
type=karaf.feature; version="[0,0.0.0]"; filter:="(&(osgi.identity=f10e4260-a93a-4d78-beb5-cb17edbd7ce5)(type=karaf.feature)(version>=0.0.0)(version<=0.0.0))"
[caused by: Unable to resolve
f10e4260-a93a-4d78-beb5-cb17edbd7ce5/0.0.0: missing requirement [f10e4260-a93a-4d78-beb5-cb17edbd7ce5/0.0.0] osgi.identity; osgi.identity=odl-transportpce; type=karaf.feature; version="[3.0.0.SNAPSHOT,3.0.0.SNAPSHOT]" [caused by: Unable to resolve odl-transportpce/3.0.0.SNAPSHOT: missing requirement [odl-transportpce/3.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.opendaylight.transportpce.networkmodel;
type=osgi.bundle; version="[3.0.0.SNAPSHOT,3.0.0.SNAPSHOT]";
resolution:=mandatory [caused by: Unable to resolve
org.opendaylight.transportpce.networkmodel/3.0.0.SNAPSHOT: missing requirement [org.opendaylight.transportpce.networkmodel/3.0.0.SNAPSHOT]
osgi.wiring.package;
filter:="(&(osgi.wiring.package=org.opendaylight.yang.gen.v1.urn.opendaylight.netconf.node.topology.rev150114)(version>=1.13.0)(!(version>=2.0.0)))"
[caused by: Unable to resolve
org.opendaylight.netconf.sal-netconf-connector/1.13.0.SNAPSHOT:
missing requirement
[org.opendaylight.netconf.sal-netconf-connector/1.13.0.SNAPSHOT]
osgi.wiring.package;
filter:="(&(osgi.wiring.package=org.opendaylight.netconf.client)(version>=1.13.0)(!(version>=2.0.0)))"]]]]
    at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
    at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:434)
    at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:421)
    at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
    at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
    at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:392)
    at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
    at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve f10e4260-a93a-4d78-beb5-cb17edbd7ce5/0.0.0: missing requirement [f10e4260-a93a-4d78-beb5-cb17edbd7ce5/0.0.0]
osgi.identity; osgi.identity=odl-transportpce; type=karaf.feature; version="[3.0.0.SNAPSHOT,3.0.0.SNAPSHOT]" [caused by: Unable to resolve odl-transportpce/3.0.0.SNAPSHOT: missing requirement [odl-transportpce/3.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.opendaylight.transportpce.networkmodel;
type=osgi.bundle; version="[3.0.0.SNAPSHOT,3.0.0.SNAPSHOT]";
resolution:=mandatory [caused by: Unable to resolve
org.opendaylight.transportpce.networkmodel/3.0.0.SNAPSHOT: missing requirement [org.opendaylight.transportpce.networkmodel/3.0.0.SNAPSHOT]
osgi.wiring.package;
filter:="(&(osgi.wiring.package=org.opendaylight.yang.gen.v1.urn.opendaylight.netconf.node.topology.rev150114)(version>=1.13.0)(!(version>=2.0.0)))"
[caused by: Unable to resolve
org.opendaylight.netconf.sal-netconf-connector/1.13.0.SNAPSHOT:
missing requirement
[org.opendaylight.netconf.sal-netconf-connector/1.13.0.SNAPSHOT]
osgi.wiring.package;
filter:="(&(osgi.wiring.package=org.opendaylight.netconf.client)(version>=1.13.0)(!(version>=2.0.0)))"]]]
    at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
    ... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve odl-transportpce/3.0.0.SNAPSHOT: missing requirement [odl-transportpce/3.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.opendaylight.transportpce.networkmodel;
type=osgi.bundle; version="[3.0.0.SNAPSHOT,3.0.0.SNAPSHOT]";
resolution:=mandatory [caused by: Unable to resolve
org.opendaylight.transportpce.networkmodel/3.0.0.SNAPSHOT: missing requirement [org.opendaylight.transportpce.networkmodel/3.0.0.SNAPSHOT]
osgi.wiring.package;
filter:="(&(osgi.wiring.package=org.opendaylight.yang.gen.v1.urn.opendaylight.netconf.node.topology.rev150114)(version>=1.13.0)(!(version>=2.0.0)))"
[caused by: Unable to resolve
org.opendaylight.netconf.sal-netconf-connector/1.13.0.SNAPSHOT:
missing requirement
[org.opendaylight.netconf.sal-netconf-connector/1.13.0.SNAPSHOT]
osgi.wiring.package;
filter:="(&(osgi.wiring.package=org.opendaylight.netconf.client)(version>=1.13.0)(!(version>=2.0.0)))"]]
    at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
    ... 13 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.opendaylight.transportpce.networkmodel/3.0.0.SNAPSHOT:
missing requirement
[org.opendaylight.transportpce.networkmodel/3.0.0.SNAPSHOT]
osgi.wiring.package;
filter:="(&(osgi.wiring.package=org.opendaylight.yang.gen.v1.urn.opendaylight.netconf.node.topology.rev150114)(version>=1.13.0)(!(version>=2.0.0)))"
[caused by: Unable to resolve
org.opendaylight.netconf.sal-netconf-connector/1.13.0.SNAPSHOT:
missing requirement
[org.opendaylight.netconf.sal-netconf-connector/1.13.0.SNAPSHOT]
osgi.wiring.package;
filter:="(&(osgi.wiring.package=org.opendaylight.netconf.client)(version>=1.13.0)(!(version>=2.0.0)))"]
    at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
    ... 14 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.opendaylight.netconf.sal-netconf-connector/1.13.0.SNAPSHOT:
missing requirement
[org.opendaylight.netconf.sal-netconf-connector/1.13.0.SNAPSHOT]
osgi.wiring.package;
filter:="(&(osgi.wiring.package=org.opendaylight.netconf.client)(version>=1.13.0)(!(version>=2.0.0)))"
    at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
    ... 15 more

Patch-set: 2