Update patch set 4
Patch Set 4: Verified-1

$ tox -e portmapping
$ cat odl.log
[..]
 INFO [opendaylight-cluster-data-notification-dispatcher-43] (AbstractNetconfTopology.java:252) - Concurrent rpc limit is smaller than 1, no limit will be enforced for device RemoteDevice{XPDRA01}
 INFO [opendaylight-cluster-data-notification-dispatcher-43] (NetConfTopologyListener.java:220) - onDataTreeChanged
 INFO [opendaylight-cluster-data-notification-dispatcher-43] (NetConfTopologyListener.java:244) - Node added: XPDRA01
ERROR [opendaylight-cluster-data-notification-dispatcher-43] (NetConfTopologyListener.java:275) - Cannot get available Capabilities
 WARN [sshd-NetconfSshClient[4e4e7fbb]-nio2-thread-3] (StaticServerKeyVerifier.java:59) - Server at /127.0.0.1:17830 presented unverified RSA key: SHA256:nbxFM93XYUAMuz300QWI5KkHzn1wnp9JUo7YqjUuQTE
 WARN [default-pool-5-2] (DeviceSourcesResolver.java:60) - RemoteDevice{XPDRA01}: Netconf device does not provide all yang models reported in hello message capabilities, required but not provided: [(urn:ietf:params:xml:ns:netmod:notification?revision=2008-07-14)nc-notifications, (urn:ietf:params:xml:ns:yang:ietf-restconf-monitoring?revision=2017-01-26)ietf-restconf-monitoring, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)network-topology, (urn:ietf:params:xml:ns:yang:ietf-yang-library?revision=2016-06-21)ietf-yang-library, (urn:opendaylight:params:xml:ns:yang:mdsal:core:general-entity?revision=2015-09-30)odl-general-entity]
 WARN [default-pool-5-2] (DeviceSourcesResolver.java:62) - RemoteDevice{XPDRA01}: Attempting to build schema context from required sources
 INFO [default-pool-5-2] (NetconfDevice.java:267) - RemoteDevice{XPDRA01}: Netconf connector initialized successfully
 INFO [opendaylight-cluster-data-notification-dispatcher-38] (NetConfTopologyListener.java:220) - onDataTreeChanged
 INFO [opendaylight-cluster-data-notification-dispatcher-38] (NetConfTopologyListener.java:244) - Node added: XPDRA01
 INFO [opendaylight-cluster-data-notification-dispatcher-38] (NetConfTopologyListener.java:256) - OpenROADM node detected: XPDRA01 Connected
 INFO [opendaylight-cluster-data-notification-dispatcher-38] (NetworkModelServiceImpl.java:91) - createOpenROADMNode: XPDRA01 
 INFO [opendaylight-cluster-data-notification-dispatcher-38] (PortMappingVersion121.java:106) - Create Mapping Data for node 1.2.1 XPDRA01
 WARN [opendaylight-cluster-data-notification-dispatcher-38] (PortMappingVersion121.java:219) - Ports were not found for circuit pack: 1/0
 WARN [opendaylight-cluster-data-notification-dispatcher-38] (PortMappingVersion121.java:219) - Ports were not found for circuit pack: 1/0/PWR
Uncaught error from thread [opendaylight-cluster-data-notification-dispatcher-38]: 'java.util.Map org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.portmapping.rev200827.network.nodes.Mapping.augmentations()', shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[opendaylight-cluster-data]
java.lang.NoSuchMethodError: 'java.util.Map org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.portmapping.rev200827.network.nodes.Mapping.augmentations()'
	at org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.portmapping.rev200827.network.nodes.MappingBuilder.<init>(MappingBuilder.java:84)
	at org.opendaylight.transportpce.common.mapping.PortMappingVersion121.createXpdrMappingObject(PortMappingVersion121.java:691)
	at org.opendaylight.transportpce.common.mapping.PortMappingVersion121.createXpdrPortMapping(PortMappingVersion121.java:321)
	at org.opendaylight.transportpce.common.mapping.PortMappingVersion121.createMappingData(PortMappingVersion121.java:144)
	at org.opendaylight.transportpce.common.mapping.PortMappingImpl.createMappingData(PortMappingImpl.java:54)
	at org.opendaylight.transportpce.networkmodel.service.NetworkModelServiceImpl.createOpenRoadmNode(NetworkModelServiceImpl.java:93)
	at org.opendaylight.transportpce.networkmodel.NetConfTopologyListener.onDataTreeChanged(NetConfTopologyListener.java:259)
	at org.opendaylight.mdsal.binding.dom.adapter.BindingDOMDataTreeChangeListenerAdapter.onDataTreeChanged(BindingDOMDataTreeChangeListenerAdapter.java:37)
	at org.opendaylight.controller.cluster.datastore.DataTreeChangeListenerActor.dataTreeChanged(DataTreeChangeListenerActor.java:83)
	at org.opendaylight.controller.cluster.datastore.DataTreeChangeListenerActor.handleReceive(DataTreeChangeListenerActor.java:44)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:242)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:227)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
 INFO [Thread-18] (Main.java:162) - lighty.io and RESTCONF-NETCONF shutting down ...
 INFO [Thread-18] (AbstractLightyModule.java:160) - Submitted shutdown of LightyModule TransportPCEImpl.
 INFO [pool-23-thread-1] (TapiProvider.java:69) - TapiProvider Session Closed
 INFO [pool-23-thread-1] (TransportPCEImpl.java:184) - Shutting down service-handler provider ...
 INFO [pool-23-thread-1] (ServicehandlerProvider.java:85) - ServicehandlerProvider Closed
ERROR [opendaylight-cluster-data-akka.actor.default-dispatcher-18] (MarkerIgnoringBase.java:159) - Uncaught error from thread [opendaylight-cluster-data-notification-dispatcher-38]: 'java.util.Map org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.portmapping.rev200827.network.nodes.Mapping.augmentations()', shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[opendaylight-cluster-data]
java.lang.NoSuchMethodError: 'java.util.Map org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.portmapping.rev200827.network.nodes.Mapping.augmentations()'
	at org.opendaylight.yang.gen.v1.http.org.opendaylight.transportpce.portmapping.rev200827.network.nodes.MappingBuilder.<init>(MappingBuilder.java:84)
	at org.opendaylight.transportpce.common.mapping.PortMappingVersion121.createXpdrMappingObject(PortMappingVersion121.java:691)
	at org.opendaylight.transportpce.common.mapping.PortMappingVersion121.createXpdrPortMapping(PortMappingVersion121.java:321)
	at org.opendaylight.transportpce.common.mapping.PortMappingVersion121.createMappingData(PortMappingVersion121.java:144)
	at org.opendaylight.transportpce.common.mapping.PortMappingImpl.createMappingData(PortMappingImpl.java:54)
	at org.opendaylight.transportpce.networkmodel.service.NetworkModelServiceImpl.createOpenRoadmNode(NetworkModelServiceImpl.java:93)
	at org.opendaylight.transportpce.networkmodel.NetConfTopologyListener.onDataTreeChanged(NetConfTopologyListener.java:259)
	at org.opendaylight.mdsal.binding.dom.adapter.BindingDOMDataTreeChangeListenerAdapter.onDataTreeChanged(BindingDOMDataTreeChangeListenerAdapter.java:37)
	at org.opendaylight.controller.cluster.datastore.DataTreeChangeListenerActor.dataTreeChanged(DataTreeChangeListenerActor.java:83)
	at org.opendaylight.controller.cluster.datastore.DataTreeChangeListenerActor.handleReceive(DataTreeChangeListenerActor.java:44)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:187)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:186)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:241)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:242)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:227)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
 INFO [pool-23-thread-1] (TransportPCEImpl.java:186) - Shutting down renderer provider ...
 [...]

Patch-set: 4
Reviewer: Gerrit User 7446 <7446@7fc14799-209e-464c-9743-7a06c2c21a81>
Reviewer: Gerrit User 8630 <8630@7fc14799-209e-464c-9743-7a06c2c21a81>
Reviewer: Gerrit User 6731 <6731@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=-1