Update patch set 3
Patch Set 3: -Verified Code-Review+1

> Patch Set 3:
> 
> gnpy runtests: commands[3] | nosetests --with-xunit transportpce_tests/1.2.1/test_gnpy.py
> ....FFF...
> ======================================================================
> FAIL: test_05_path_computation_FoundByPCE_NotFeasibleByGnpy (test_gnpy.TransportGNPYtesting)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/guillaume/git_ws/ws_20200226/master/transportpce/tests/transportpce_tests/1.2.1/test_gnpy.py", line 193, in test_05_path_computation_FoundByPCE_NotFeasibleByGnpy
>     self.assertEqual(res['output']['configuration-response-common']['response-code'], '500')
> AssertionError: '200' != '500'
> - 200
> ? ^
> + 500
> ? ^
> 
> -------------------- >> begin captured logging << --------------------
> urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8181
> urllib3.connectionpool: DEBUG: http://localhost:8181 "POST /restconf/operations/transportpce-pce:path-computation-request HTTP/1.1" 200 None
> --------------------- >> end captured logging << ---------------------
> 
> ======================================================================
> FAIL: test_06_path_computation_NotFoundByPCE_FoundByGNPy (test_gnpy.TransportGNPYtesting)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/guillaume/git_ws/ws_20200226/master/transportpce/tests/transportpce_tests/1.2.1/test_gnpy.py", line 254, in test_06_path_computation_NotFoundByPCE_FoundByGNPy
>     'Path is calculated by GNPy')
> AssertionError: 'Path is calculated by PCE' != 'Path is calculated by GNPy'
> - Path is calculated by PCE
> ?                        ^^
> + Path is calculated by GNPy
> ?                       ++ ^
> 
> -------------------- >> begin captured logging << --------------------
> urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8181
> urllib3.connectionpool: DEBUG: http://localhost:8181 "POST /restconf/operations/transportpce-pce:path-computation-request HTTP/1.1" 200 6031
> --------------------- >> end captured logging << ---------------------
> 
> ======================================================================
> FAIL: test_07_path_computation_FoundByPCE_NotFeasibleByGnpy (test_gnpy.TransportGNPYtesting)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/guillaume/git_ws/ws_20200226/master/transportpce/tests/transportpce_tests/1.2.1/test_gnpy.py", line 325, in test_07_path_computation_FoundByPCE_NotFeasibleByGnpy
>     'No path available by PCE and GNPy ')
> AssertionError: 'No path available by PCE' != 'No path available by PCE and GNPy '
> - No path available by PCE
> + No path available by PCE and GNPy 
> ?                         ++++++++++
> 
> -------------------- >> begin captured logging << --------------------
> urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8181
> urllib3.connectionpool: DEBUG: http://localhost:8181 "POST /restconf/operations/transportpce-pce:path-computation-request HTTP/1.1" 200 167
> --------------------- >> end captured logging << ---------------------
> 
> ----------------------------------------------------------------------
> Ran 10 tests in 82.056s
> 
> FAILED (failures=3)

this needs to be confirmed by Ahmed and fixed in another change

Patch-set: 3
Reviewer: Gerrit User 6731 <6731@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=0
Label: Code-Review=+1