Update patch set 9
Patch Set 9:

This change was working correctly until the merge of change 93576.
Actually, it is always working correctly with karaf, but is failing when we use TransportPCE with Lighty. Indeed, with lighty, Portmapping does no longer work for device in version 7.1. It seems to be due to a problem with the org-openroadm-device model in rev200529...

ERROR [opendaylight-cluster-data-notification-dispatcher-40] (DataTreeChangeListenerActor.java:85) - member-1-shard-topology-operational: Error notifying listener org.opendaylight.mdsal.binding.dom.adapter.BindingDOMDataTreeChangeListenerAdapter@7d043788
org.opendaylight.mdsal.binding.dom.codec.api.MissingSchemaForClassException: Schema is not available for interface org.opendaylight.yang.gen.v1.http.org.openroadm.device.rev200529.org.openroadm.device.container.OrgOpenroadmDevice
	at org.opendaylight.mdsal.binding.dom.codec.impl.DataContainerCodecContext.childNullException(DataContainerCodecContext.java:211)
	at org.opendaylight.mdsal.binding.dom.codec.impl.DataContainerCodecContext.childNonNull(DataContainerCodecContext.java:188)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext.createDataTreeChildContext(SchemaRootCodecContext.java:191)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext$1.load(SchemaRootCodecContext.java:67)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext$1.load(SchemaRootCodecContext.java:58)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext.getOrRethrow(SchemaRootCodecContext.java:321)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext.streamChild(SchemaRootCodecContext.java:150)
	at org.opendaylight.mdsal.binding.dom.codec.impl.DataContainerCodecContext.bindingPathArgumentChild(DataContainerCodecContext.java:113)
	at org.opendaylight.mdsal.binding.dom.codec.impl.SchemaRootCodecContext.bindingPathArgumentChild(SchemaRootCodecContext.java:303)
	at org.opendaylight.mdsal.binding.dom.codec.impl.BindingCodecContext.getCodecContextNode(BindingCodecContext.java:241)
	at org.opendaylight.mdsal.binding.dom.codec.impl.InstanceIdentifierCodec.fromBinding(InstanceIdentifierCodec.java:53)
	at org.opendaylight.mdsal.binding.dom.codec.impl.BindingCodecContext.toYangInstanceIdentifier(BindingCodecContext.java:485)
	at org.opendaylight.mdsal.binding.dom.codec.spi.ForwardingBindingDOMCodecServices.toYangInstanceIdentifier(ForwardingBindingDOMCodecServices.java:55)
	at org.opendaylight.mdsal.binding.dom.adapter.AbstractForwardedTransaction.doRead(AbstractForwardedTransaction.java:73)
	at org.opendaylight.mdsal.binding.dom.adapter.BindingDOMReadWriteTransactionAdapter.read(BindingDOMReadWriteTransactionAdapter.java:31)
	at org.opendaylight.transportpce.common.device.DeviceTransaction.read(DeviceTransaction.java:58)
	at org.opendaylight.transportpce.common.device.DeviceTransactionManagerImpl.getDataFromDevice(DeviceTransactionManagerImpl.java:161)
	at org.opendaylight.transportpce.common.mapping.PortMappingVersion710.createMappingData(PortMappingVersion710.java:131)
	at org.opendaylight.transportpce.common.mapping.PortMappingImpl.createMappingData(PortMappingImpl.java:63)
...

Patch-set: 9