Update patch set 26
Patch Set 26:

That's probably timeout issues 
but the testing configuration used is dual CPU with 10 cores + 64 GB RAM...

It may be due to some initialization phase that can be longer on such big configurations.


> Patch Set 26:
> 
> Those errors are probably from the fact that there was timeout exception on datastore writting transaction. If you check tpce log file you will probably find those exceptions. Those exceptions happen when the computer running tpce is too slow.
> > Patch Set 26: Verified-1
> > 
> > Creating nbinotifications_zookeeper_1 ... done
> > Creating nbinotifications_kafka_1     ... done
> > nbinotifications runtests: commands[8] | nosetests --with-xunit transportpce_tests/2.2.1/test_nbinotifications.py
> > client: JAVA_HOME not set; results may vary
> >                                                                                            
> >     ________                       ________                .__  .__       .__     __       
> >     \_____  \ ______   ____   ____ \______ \ _____  ___.__.|  | |__| ____ |  |___/  |_     
> >      /   |   \\____ \_/ __ \ /    \ |    |  \\__  \<   |  ||  | |  |/ ___\|  |  \   __\    
> >     /    |    \  |_> >  ___/|   |  \|    `   \/ __ \\___  ||  |_|  / /_/  >   Y  \  |      
> >     \_______  /   __/ \___  >___|  /_______  (____  / ____||____/__\___  /|___|  /__|      
> >             \/|__|        \/     \/        \/     \/\/            /_____/      \/          
> >                                                                                            
> > 
> > Hit '<tab>' for a list of available commands
> > and '[cmd] --help' for help on a specific command.
> > Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown OpenDaylight.
> > 
> > opendaylight-user@root>feature:install odl-transportpce-nbinotifications
> > opendaylight-user@root> feature:list | grep tapi 
> > odl-transportpce-tapi                                           │ 3.0.0.SNAPSHOT   │          │ Uninstalled │ odl-transportpce-tapi                                           │ OpenDaylight :: transportpce :: tapi
> > opendaylight-user@root> logout 
> > ..........E....E.F....
> > ======================================================================
> > ERROR: test_11_get_notifications_service1 (test_nbinotifications.TransportNbiNotificationstesting)
> > ----------------------------------------------------------------------
> > Traceback (most recent call last):
> >   File "/home/guillaume/git_ws/transportpce/tests/transportpce_tests/2.2.1/test_nbinotifications.py", line 227, in test_11_get_notifications_service1
> >     self.assertEqual(res['output']['notification-service'][-2]['service-name'], 'service1')
> > IndexError: list index out of range
> > -------------------- >> begin captured stdout << ---------------------
> > execution of test_11_get_notifications_service1
> > {"input": {"connection-type": "service", "id-consumer": "consumer", "group-id": "transportpceTest"}}
> > 
> > --------------------- >> end captured stdout << ----------------------
> > -------------------- >> begin captured logging << --------------------
> > urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8181
> > urllib3.connectionpool: DEBUG: http://localhost:8181 "POST /restconf/operations/nbi-notifications:get-notifications-service/ HTTP/1.1" 200 1690
> > --------------------- >> end captured logging << ---------------------
> > 
> > ======================================================================
> > ERROR: test_16_get_notifications_service1 (test_nbinotifications.TransportNbiNotificationstesting)
> > ----------------------------------------------------------------------
> > Traceback (most recent call last):
> >   File "/home/guillaume/git_ws/transportpce/tests/transportpce_tests/2.2.1/test_nbinotifications.py", line 303, in test_16_get_notifications_service1
> >     self.assertEqual(res['output']['notification-service'][-3]['message'], 'ServiceCreate request received ...')
> > KeyError: 'message'
> > -------------------- >> begin captured stdout << ---------------------
> > execution of test_16_get_notifications_service1
> > {"input": {"connection-type": "service", "id-consumer": "consumer", "group-id": "transportpceTest"}}
> > 
> > --------------------- >> end captured stdout << ----------------------
> > -------------------- >> begin captured logging << --------------------
> > urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8181
> > urllib3.connectionpool: DEBUG: http://localhost:8181 "POST /restconf/operations/nbi-notifications:get-notifications-service/ HTTP/1.1" 200 5177
> > --------------------- >> end captured logging << ---------------------
> > 
> > ======================================================================
> > FAIL: test_18_get_notifications_service1 (test_nbinotifications.TransportNbiNotificationstesting)
> > ----------------------------------------------------------------------
> > Traceback (most recent call last):
> >   File "/home/guillaume/git_ws/transportpce/tests/transportpce_tests/2.2.1/test_nbinotifications.py", line 331, in test_18_get_notifications_service1
> >     self.assertEqual(res['output']['notification-service'][-2]['message'], 'ServiceDelete request received ...')
> > AssertionError: 'Service implemented !' != 'ServiceDelete request received ...'
> > - Service implemented !
> > + ServiceDelete request received ...
> > 
> > -------------------- >> begin captured stdout << ---------------------
> > execution of test_18_get_notifications_service1
> > {"input": {"connection-type": "service", "id-consumer": "consumer", "group-id": "transportpceTest"}}
> > 
> > --------------------- >> end captured stdout << ----------------------
> > -------------------- >> begin captured logging << --------------------
> > urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8181
> > urllib3.connectionpool: DEBUG: http://localhost:8181 "POST /restconf/operations/nbi-notifications:get-notifications-service/ HTTP/1.1" 200 6912
> > --------------------- >> end captured logging << ---------------------
> > 
> > ----------------------------------------------------------------------
> > Ran 22 tests in 217.129s
> > 
> > FAILED (errors=2, failures=1)

Patch-set: 26
Reviewer: Gerrit User 6731 <6731@7fc14799-209e-464c-9743-7a06c2c21a81>